GET https://merchant.wish.com/api/v3/products/604b08566dc1ff54efd00169
Authorization: Bearer 0c2d0ad8d6454d8aa9ccc9c17f7076fa

###

GET https://merchant.wish.com/api/v3/merchant/warehouses
Authorization: Bearer f3424ebd7b9844b7ba78a2a91d722692